version: '3'

networks:
  u-blog_network:
    driver: bridge

services:

  # NGINX - Service
  nginx:
    container_name: ublog_webserver
    image: nginx:stable-alpine

    ports:
      - '8080:80'

    volumes:
      - ./:/var/www/u-blog_docker
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - php
      - mysql

    networks:
      - u-blog_network

  # MYSQL – Service
  mysql:
    container_name: database
    image: mysql:5.7.22
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: u-blog_db
      MYSQL_USER: root
      MYSQL_PASSWORD: secret

    ports:
      - '4306:3306'

    volumes:
      - ./mysql:/var/lib/mysql

    networks:
      - u-blog_network

  # PHP-FPM - Service
  php:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: u-blog

    ports:
      - '9000:9000'

    volumes:
      - ./:/var/www/u-blog_docker

    depends_on:
      - mysql

    networks:
      - u-blog_network
